### ISSUE TITLE
cosidering large chunk？

### ISSUE THREAD

**Issue by bigbrother666sh** [junruxiong/IncarnaMind#8]
Considering that llms support longer context, would it be more ideal if we change our document chunk scheme to segment by natural paragraphs instead of natural sentences (,)?

**Comment by junruxiong** [comment]
It can be a tricky problem to try to split the text into natural paragraphs because the format of each document is different. Currently, the feasible methods mainly involve extracting based on new lines/titles or using OCR layout analysis. The first rule-based approach might not be robust enough, while the second approach requires high computational and time-consuming, taking at least 1-2 seconds per page on consumer-level computers. 

IncarnaMind leverages (1) small chunks to locate documents and (2) sliding windows to identify potential large chunks (you can consider the large chunks as sections) given the retrieved document filter. (3) Finally, retrieve medium-sized chunks from the filtered text by document name and large chunk indices to answer the user's questions using LLMs.

But, of course, you can define your own small, medium and large chunk size using the [configparser.ini](https://github.com/junruxiong/IncarnaMind/blob/main/configparser.ini).

Please do not hesitate to contact me here or junruxiong@gmail, if you have any further concerns or suggestions!

**Comment by bigbrother666sh** [comment]
thanks for your reply.
From my understanding, the industry is currently mostly using the first solution, but the future should belong to the second solution. As for the solution proposed by IncarnaMind, although it is very innovative, it inevitably introduces cluttered or missing information in the retrieve stage, which cannot be avoided no matter how the chunk size is adjusted. I don’t know how you think about this.

**Comment by bigbrother666sh** [comment]
So my suggestion is to make small-chunk according to the principle of natural sentences, and then add a natural number parameter N, and the N sentences before and after the natural sentence are combined into medium-chunk...
